### ISSUE TITLE
第一份建议 (･∀･) suggestions

### ISSUE THREAD

**Issue by v2Binarization** [Jackeriss/Top15#2]
1. '`douban.jackeriss.com, cdn.jackeriss.com, top15.jackeriss.com`' 给它们颁发一个可信任的HTTPS证书吧。（Wosgin \ StartSSL \ CloudFlare \ Let’s Encrypt 免费证书。）

2. 然后完美支持HTTPS。用 `//top15.jackeriss.com/` 而不是 `http://top15.jackeriss.com/`。

3. 我在 `.openshift/cron/daily/updateAll.sh` 添加了`$OPENSHIFT_REPO_DIR`用于替换`/var/lib/openshift/579477917628e19db600000d/app-root/runtime/repo`

暂时就这些了。

我在Open shift照样搭建了一个，环境是py3.3。好像没有安装成功... 可能是qiniu_api 没有配置吧。
另外，还想问下 `douban.jackeriss.com` 是怎么搭建的，因为我想如法炮制一个HTTPS可访站点。

(･∀･)

**Comment by Jackeriss** [comment]
感谢你的建议，过两天到学校后再弄，我的 openshift 应用环境是 flask , douban.jackeriss.com 是一个七牛存储空间绑定的域名，使用 CNAME 绑定即可。

**Comment by Jackeriss** [comment]
@v2Binarization OpenShift 免费账户不支持给自己绑定的域名添加证书 ⊙﹏⊙

**Comment by v2Binarization** [comment]
免费版确实不能。免费用户可以绑定信用卡进而开通免费的铜牌计划，然而用CloudFlare做跳板则更为简单。
